config/routes.rb
Rails.application.routes.draw do
  get 'oauth/authorize'

  resources :item_options
  get 'welcome/index'

  resources :fb_users
  resources :brands
  mount Facebook::Messenger::Server, at: 'messenger'

  root 'welcome#index'

end

app/models/fb_user.rb
class FbUser < ActiveRecord::Base
	has_many :matches

	def matching_items
		options = %i{color platform camera price_category sim_count cpu_category}
		where = []
		args = []
		options.each do |option|
			value = self.attributes[option.to_s]
			unless value.nil?
				where.push('(key = ? AND value = ?)')
				args.push(option, value)
			end
		end
		item_ids = ItemOption.where(where.join(' OR '), *args).group(:item_id).order('COUNT(*) DESC').limit(3).pluck(:item_id)
		Item.where(id: item_ids)
	end
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :matches
end

app/models/item_option.rb
class ItemOption < ActiveRecord::Base
end

app/models/match.rb
class Match < ActiveRecord::Base
	belongs_to :user
	belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/item_options_controller.rb
class ItemOptionsController < ApplicationController
  before_action :set_item_option, only: [:show, :edit, :update, :destroy]

  # GET /item_options
  # GET /item_options.json
  def index
    @item_options = ItemOption.all
  end

  # GET /item_options/1
  # GET /item_options/1.json
  def show
  end

  # GET /item_options/new
  def new
    @item_option = ItemOption.new
  end

  # GET /item_options/1/edit
  def edit
  end

  # POST /item_options
  # POST /item_options.json
  def create
    @item_option = ItemOption.new(item_option_params)

    respond_to do |format|
      if @item_option.save
        format.html { redirect_to @item_option, notice: 'Item option was successfully created.' }
        format.json { render :show, status: :created, location: @item_option }
      else
        format.html { render :new }
        format.json { render json: @item_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_options/1
  # PATCH/PUT /item_options/1.json
  def update
    respond_to do |format|
      if @item_option.update(item_option_params)
        format.html { redirect_to @item_option, notice: 'Item option was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_option }
      else
        format.html { render :edit }
        format.json { render json: @item_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_options/1
  # DELETE /item_options/1.json
  def destroy
    @item_option.destroy
    respond_to do |format|
      format.html { redirect_to item_options_url, notice: 'Item option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_option
      @item_option = ItemOption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_option_params
      params.fetch(:item_option, {})
    end
end

app/controllers/messenger_controller.rb
class MessengerController < ApplicationController

  skip_before_filter :verify_authenticity_token

  def webhook
    # if params['hub.mode'] == 'subscribe' && params['hub.verify_token'] == ENV['MESSENGER_VERIFY_TOKEN']
    #   render text: params['hub.challenge'], status: 200
    # else
    #   render nothing: true, status: 403
    # end

    if params['object'] == 'page'
      render nothing: true, status: 200
    end

  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  before_action :require_login

  def authorize
    auth_code = "test_#{current_user.id}"
    current_user.update(
      account_linking_token: params['account_linking_token'],
      auth_code: auth_code
    )
    redirect_to params['redirect_uri'] + "&authorization_code=#{auth_code}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @brands = @user.matching_brands
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/item_options_helper.rb
module ItemOptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Brands</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>

app/views/item_options/_form.html.erb
<%= form_for(@item_option) do |f| %>
  <% if @item_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_option.errors.count, "error") %> prohibited this item_option from being saved:</h2>

      <ul>
      <% @item_option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_options/edit.html.erb
<h1>Editing Item Option</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_option %> |
<%= link_to 'Back', item_options_path %>

app/views/item_options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Item Options</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_options.each do |item_option| %>
      <tr>
        <td><%= link_to 'Show', item_option %></td>
        <td><%= link_to 'Edit', edit_item_option_path(item_option) %></td>
        <td><%= link_to 'Destroy', item_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item option', new_item_option_path %>

app/views/item_options/new.html.erb
<h1>New Item Option</h1>

<%= render 'form' %>

<%= link_to 'Back', item_options_path %>

app/views/item_options/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_item_option_path(@item_option) %> |
<%= link_to 'Back', item_options_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lazada Test</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

Brands:
<ul>
<% @brands.each do |brand| %>
    <li><%= brand.name %></li>
<% end %>
</ul>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1091621010957932',
      xfbml      : true,
      version    : 'v2.6'
    });
  };

  (function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<div class="fb-send-to-messenger"
     messenger_app_id="1091621010957932"
     page_id="255096811549063"
     data-ref="FROM_SITE"
     color="blue"
     size="standard"></div>


<div class="fb-messengermessageus"
     messenger_app_id="1091621010957932"
     page_id="255096811549063"
     color="blue"
     size="standard" ></div>

<% if signed_in? %>
    <%= current_user.email %>
    <%= button_to "Sign out", sign_out_path, method: :delete %>
<% else %>
    <%= link_to "Sign in", sign_in_path %>
<% end %>